### ISSUE TITLE
MendSlice *might* be UB.

### ISSUE THREAD

**Issue by eddyb** [bluss/odds#25]
IIUC, it's fine within a memory allocation (what C calls "an object"), but across them, you're usually not allowed to do a lot. cc @RalfJung @solson

**Comment by bluss** [comment]
Good point, makes sense

**Comment by eddyb** [comment]
Note that I'm not sure, hoping @RalfJung can answer, or bring up in "unsafe code guidelines" discussions.

**Comment by bluss** [comment]
Context link to the docs https://docs.rs/odds/0.3.1/odds/slice/struct.MendSlices.html

**Comment by RalfJung** [comment]
What exactly is `mend_slices` doing? The docs link to https://docs.rs/odds/0.3.1/odds/trait.Itertools.html#method.mend_slices but that doesn't exist.

**Comment by RalfJung** [comment]
Oh I think I found it at https://docs.rs/odds/0.3.1/src/odds/slice/mod.rs.html#309

Yeah I think this doesn't work. So you are comparing the end address of one slice with the beginning of another. That's an extremely gray area of memory models -- an area where C and C++ differ and we have no idea what the heck LLVM implements. But LLVM is pretty clear that you can do `getelementptr` only within an allocation, so if it *happens* to be the case that two allocations exist right next to each other, and you "mend" them together, I am pretty sure you are on UB territory here.

The funny thing is that this will actually work reliably on miri because that assumes allocations never sit right next to each other. ;)

**Comment by bluss** [comment]
It's very old code, don't think it is used. It can be removed if this library is updated, because I think mend_slices was more of a cool trick and not a utility.

Is the whole stack an allocation? I assume we are not allowed to "mend" together slices of two adjacent arrays on the stack.

**Comment by RalfJung** [comment]
> Is the whole stack an allocation?

No. Every local variable is its own allocation.

**Comment by HeroicKatora** [comment]
The code here unfortunately does not only exhibit UB for the cases of mending separate allocations. It does not ensure that `a.len() + b.len()` does not lead to a slice which has more than `isize::MAX` bytes. This is somewhat curious for ZSTs.

**Comment by RalfJung** [comment]
Also see https://github.com/oberien/str-concat/issues/8
